/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_interface_bv (void)
{
  GtkWidget *window_interface_bv;
  GtkWidget *notebook2;
  GtkWidget *viewport1;
  GtkWidget *fixed2;
  GtkWidget *treeview2_admin_gbv;
  GtkWidget *entry3;
  GtkWidget *button6_admin_gbv_creer;
  GtkWidget *button2_admin_gbv_spprimer;
  GtkWidget *button_affihcher_bv;
  GtkWidget *button7_admin_gbv_modifier;
  GtkWidget *button3_admin_gbv_recherche;
  GtkWidget *button6_actualiser_bv;
  GtkWidget *label4_admin_gbv;

  window_interface_bv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_interface_bv), _("interface admin"));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (window_interface_bv), notebook2);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (notebook2), viewport1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed2);

  treeview2_admin_gbv = gtk_tree_view_new ();
  gtk_widget_show (treeview2_admin_gbv);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview2_admin_gbv, 104, 24);
  gtk_widget_set_size_request (treeview2_admin_gbv, 736, 424);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 704, 480);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  button6_admin_gbv_creer = gtk_button_new_with_mnemonic (_("Cr\303\251er"));
  gtk_widget_show (button6_admin_gbv_creer);
  gtk_fixed_put (GTK_FIXED (fixed2), button6_admin_gbv_creer, 144, 528);
  gtk_widget_set_size_request (button6_admin_gbv_creer, 66, 29);

  button2_admin_gbv_spprimer = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button2_admin_gbv_spprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_admin_gbv_spprimer, 896, 456);
  gtk_widget_set_size_request (button2_admin_gbv_spprimer, 96, 24);

  button_affihcher_bv = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button_affihcher_bv);
  gtk_fixed_put (GTK_FIXED (fixed2), button_affihcher_bv, 888, 512);
  gtk_widget_set_size_request (button_affihcher_bv, 120, 24);

  button7_admin_gbv_modifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button7_admin_gbv_modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), button7_admin_gbv_modifier, 888, 552);
  gtk_widget_set_size_request (button7_admin_gbv_modifier, 96, 24);

  button3_admin_gbv_recherche = gtk_button_new_with_mnemonic (_("recherche"));
  gtk_widget_show (button3_admin_gbv_recherche);
  gtk_fixed_put (GTK_FIXED (fixed2), button3_admin_gbv_recherche, 912, 576);
  gtk_widget_set_size_request (button3_admin_gbv_recherche, 96, 24);

  button6_actualiser_bv = gtk_button_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (button6_actualiser_bv);
  gtk_fixed_put (GTK_FIXED (fixed2), button6_actualiser_bv, 256, 536);
  gtk_widget_set_size_request (button6_actualiser_bv, 104, 32);

  label4_admin_gbv = gtk_label_new (_("Gestion bureau de vote"));
  gtk_widget_show (label4_admin_gbv);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label4_admin_gbv);

  g_signal_connect ((gpointer) treeview2_admin_gbv, "row_activated",
                    G_CALLBACK (on_treeview2_admin_gbv_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button6_admin_gbv_creer, "clicked",
                    G_CALLBACK (on_button6_admin_gbv_creer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_admin_gbv_spprimer, "clicked",
                    G_CALLBACK (on_button2_admin_gbv_spprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affihcher_bv, "clicked",
                    G_CALLBACK (on_button_affihcher_bv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7_admin_gbv_modifier, "clicked",
                    G_CALLBACK (on_button7_admin_gbv_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_admin_gbv_recherche, "clicked",
                    G_CALLBACK (on_button3_admin_gbv_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6_actualiser_bv, "clicked",
                    G_CALLBACK (on_button6_actualiser_bv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_interface_bv, window_interface_bv, "window_interface_bv");
  GLADE_HOOKUP_OBJECT (window_interface_bv, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (window_interface_bv, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window_interface_bv, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_interface_bv, treeview2_admin_gbv, "treeview2_admin_gbv");
  GLADE_HOOKUP_OBJECT (window_interface_bv, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window_interface_bv, button6_admin_gbv_creer, "button6_admin_gbv_creer");
  GLADE_HOOKUP_OBJECT (window_interface_bv, button2_admin_gbv_spprimer, "button2_admin_gbv_spprimer");
  GLADE_HOOKUP_OBJECT (window_interface_bv, button_affihcher_bv, "button_affihcher_bv");
  GLADE_HOOKUP_OBJECT (window_interface_bv, button7_admin_gbv_modifier, "button7_admin_gbv_modifier");
  GLADE_HOOKUP_OBJECT (window_interface_bv, button3_admin_gbv_recherche, "button3_admin_gbv_recherche");
  GLADE_HOOKUP_OBJECT (window_interface_bv, button6_actualiser_bv, "button6_actualiser_bv");
  GLADE_HOOKUP_OBJECT (window_interface_bv, label4_admin_gbv, "label4_admin_gbv");

  return window_interface_bv;
}

GtkWidget*
create_Ajout_bureau_vote (void)
{
  GtkWidget *Ajout_bureau_vote;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *label2;
  GtkWidget *ajout_bureau_vote_id_bv;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *entry2;
  GtkObject *ajout_bureau_vote_cap_electeur_adj;
  GtkWidget *ajout_bureau_vote_cap_electeur;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *ajout_bureau_vote_confirmer;
  GtkWidget *ajout_bureau_vote_municipalite;
  GtkWidget *ajout_bureau_vote_2_ob;
  GSList *ajout_bureau_vote_2_ob_group = NULL;
  GtkWidget *ajout_bureau_vote_3_ob;
  GtkWidget *ajout_bureau_vote_1_ob;
  GtkWidget *ajout_bureau_vote_annuler;
  GtkWidget *label1;

  Ajout_bureau_vote = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout_bureau_vote), _("cr\303\251ation de bureau de vote"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (Ajout_bureau_vote), notebook1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  label2 = gtk_label_new (_("ID Bureu de vote"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 16, 32);
  gtk_widget_set_size_request (label2, 120, 32);

  ajout_bureau_vote_id_bv = gtk_entry_new ();
  gtk_widget_show (ajout_bureau_vote_id_bv);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_id_bv, 176, 32);
  gtk_widget_set_size_request (ajout_bureau_vote_id_bv, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajout_bureau_vote_id_bv), 8226);

  label3 = gtk_label_new (_("municipalit\303\251"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 16, 88);
  gtk_widget_set_size_request (label3, 120, 32);

  label4 = gtk_label_new (_("ID Agent"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 24, 144);
  gtk_widget_set_size_request (label4, 104, 32);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 176, 144);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  ajout_bureau_vote_cap_electeur_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  ajout_bureau_vote_cap_electeur = gtk_spin_button_new (GTK_ADJUSTMENT (ajout_bureau_vote_cap_electeur_adj), 1, 0);
  gtk_widget_show (ajout_bureau_vote_cap_electeur);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_cap_electeur, 192, 208);
  gtk_widget_set_size_request (ajout_bureau_vote_cap_electeur, 60, 27);

  label5 = gtk_label_new (_("capacit\303\251 \303\250lecteurs"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 16, 208);
  gtk_widget_set_size_request (label5, 128, 32);

  label6 = gtk_label_new (_("capacit\303\251 observateurs"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 24, 272);
  gtk_widget_set_size_request (label6, 136, 32);

  ajout_bureau_vote_confirmer = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (ajout_bureau_vote_confirmer);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_confirmer, 312, 384);
  gtk_widget_set_size_request (ajout_bureau_vote_confirmer, 66, 29);

  ajout_bureau_vote_municipalite = gtk_combo_box_new_text ();
  gtk_widget_show (ajout_bureau_vote_municipalite);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_municipalite, 184, 88);
  gtk_widget_set_size_request (ajout_bureau_vote_municipalite, 150, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("B\303\251ja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Ben Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Gab\303\251s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("K\303\251bili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Le Kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("M\303\251denine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Sidi Bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), _("Zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajout_bureau_vote_municipalite), "");

  ajout_bureau_vote_2_ob = gtk_radio_button_new_with_mnemonic (NULL, _("2 observateurs"));
  gtk_widget_show (ajout_bureau_vote_2_ob);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_2_ob, 224, 304);
  gtk_widget_set_size_request (ajout_bureau_vote_2_ob, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajout_bureau_vote_2_ob), ajout_bureau_vote_2_ob_group);
  ajout_bureau_vote_2_ob_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajout_bureau_vote_2_ob));

  ajout_bureau_vote_3_ob = gtk_radio_button_new_with_mnemonic (NULL, _("3 observateurs"));
  gtk_widget_show (ajout_bureau_vote_3_ob);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_3_ob, 224, 344);
  gtk_widget_set_size_request (ajout_bureau_vote_3_ob, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajout_bureau_vote_3_ob), ajout_bureau_vote_2_ob_group);
  ajout_bureau_vote_2_ob_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajout_bureau_vote_3_ob));

  ajout_bureau_vote_1_ob = gtk_radio_button_new_with_mnemonic (NULL, _("1 observateur"));
  gtk_widget_show (ajout_bureau_vote_1_ob);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_1_ob, 224, 264);
  gtk_widget_set_size_request (ajout_bureau_vote_1_ob, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajout_bureau_vote_1_ob), ajout_bureau_vote_2_ob_group);
  ajout_bureau_vote_2_ob_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajout_bureau_vote_1_ob));

  ajout_bureau_vote_annuler = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (ajout_bureau_vote_annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_bureau_vote_annuler, 400, 384);
  gtk_widget_set_size_request (ajout_bureau_vote_annuler, 66, 29);

  label1 = gtk_label_new (_("ajout de Bureau de vote"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  g_signal_connect ((gpointer) ajout_bureau_vote_confirmer, "clicked",
                    G_CALLBACK (on_ajout_bureau_vote_confirmer_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_bureau_vote_2_ob, "toggled",
                    G_CALLBACK (on_ajout_bureau_vote_2_ob_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajout_bureau_vote_3_ob, "toggled",
                    G_CALLBACK (on_ajout_bureau_vote_3_ob_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajout_bureau_vote_1_ob, "toggled",
                    G_CALLBACK (on_ajout_bureau_vote_1_ob_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajout_bureau_vote_annuler, "clicked",
                    G_CALLBACK (on_ajout_bureau_vote_annuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_bureau_vote, Ajout_bureau_vote, "Ajout_bureau_vote");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_id_bv, "ajout_bureau_vote_id_bv");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_cap_electeur, "ajout_bureau_vote_cap_electeur");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, label5, "label5");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, label6, "label6");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_confirmer, "ajout_bureau_vote_confirmer");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_municipalite, "ajout_bureau_vote_municipalite");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_2_ob, "ajout_bureau_vote_2_ob");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_3_ob, "ajout_bureau_vote_3_ob");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_1_ob, "ajout_bureau_vote_1_ob");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, ajout_bureau_vote_annuler, "ajout_bureau_vote_annuler");
  GLADE_HOOKUP_OBJECT (Ajout_bureau_vote, label1, "label1");

  return Ajout_bureau_vote;
}

