/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_interface_listeelectorale (void)
{
  GtkWidget *interface_listeelectorale;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *treeview_listeelecotrale;
  GtkWidget *entryidlisteelectoralerecherche;
  GtkWidget *buttonrecherchelisteelectorale;
  GtkWidget *image5;
  GtkWidget *buttontri_listeelectorale;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *buttonrefresh_listeelectorale;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;
  GtkWidget *image6;
  GtkWidget *label1;
  GtkWidget *fixed3;
  GtkWidget *entryid_listeelectorale;
  GtkWidget *entrycandidat1_listeelectorale;
  GtkWidget *entrycandidat2_listeelectorale;
  GtkWidget *entrycandidat3_listeelectorale;
  GtkObject *spinbuttonjour_listeelectorale_adj;
  GtkWidget *spinbuttonjour_listeelectorale;
  GtkObject *spinbuttonmois_listeelectorale_adj;
  GtkWidget *spinbuttonmois_listeelectorale;
  GtkObject *spinbuttonannee_listeelectorale_adj;
  GtkWidget *spinbuttonannee_listeelectorale;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *label9;
  GtkWidget *label17;
  GtkWidget *buttonajouter_listeelectorale;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *buttonmodifier_listeelectorale;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;
  GtkWidget *comboboxorientation_listeelectorale;
  GtkWidget *label2;
  GtkWidget *fixed4;
  GtkWidget *radiobuttonvoteblanc;
  GSList *radiobuttonvoteblanc_group = NULL;
  GtkWidget *radiobuttonpasdevote;
  GtkWidget *radiobuttonvoteliste;
  GtkWidget *buttongotovote;
  GtkWidget *label3;

  interface_listeelectorale = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (interface_listeelectorale), _("Liste Electorale"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (interface_listeelectorale), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1269, 789);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);
  gtk_widget_set_size_request (fixed2, 1112, 701);

  treeview_listeelecotrale = gtk_tree_view_new ();
  gtk_widget_show (treeview_listeelecotrale);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_listeelecotrale, 416, 176);
  gtk_widget_set_size_request (treeview_listeelecotrale, 504, 384);

  entryidlisteelectoralerecherche = gtk_entry_new ();
  gtk_widget_show (entryidlisteelectoralerecherche);
  gtk_fixed_put (GTK_FIXED (fixed2), entryidlisteelectoralerecherche, 544, 64);
  gtk_widget_set_size_request (entryidlisteelectoralerecherche, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidlisteelectoralerecherche), 8226);

  buttonrecherchelisteelectorale = gtk_button_new ();
  gtk_widget_show (buttonrecherchelisteelectorale);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonrecherchelisteelectorale, 720, 64);
  gtk_widget_set_size_request (buttonrecherchelisteelectorale, 40, 32);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (buttonrecherchelisteelectorale), image5);

  buttontri_listeelectorale = gtk_button_new ();
  gtk_widget_show (buttontri_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed2), buttontri_listeelectorale, 856, 56);
  gtk_widget_set_size_request (buttontri_listeelectorale, 48, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttontri_listeelectorale), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Tri"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  buttonrefresh_listeelectorale = gtk_button_new ();
  gtk_widget_show (buttonrefresh_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonrefresh_listeelectorale, 1032, 256);
  gtk_widget_set_size_request (buttonrefresh_listeelectorale, 64, 64);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonrefresh_listeelectorale), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  image6 = create_pixmap (interface_listeelectorale, "interfacele.PNG");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed2), image6, 0, 0);
  gtk_widget_set_size_request (image6, 1264, 760);

  label1 = gtk_label_new (_("Afficher"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entryid_listeelectorale = gtk_entry_new ();
  gtk_widget_show (entryid_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), entryid_listeelectorale, 456, 64);
  gtk_widget_set_size_request (entryid_listeelectorale, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid_listeelectorale), 8226);

  entrycandidat1_listeelectorale = gtk_entry_new ();
  gtk_widget_show (entrycandidat1_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), entrycandidat1_listeelectorale, 456, 224);
  gtk_widget_set_size_request (entrycandidat1_listeelectorale, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycandidat1_listeelectorale), 8226);

  entrycandidat2_listeelectorale = gtk_entry_new ();
  gtk_widget_show (entrycandidat2_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), entrycandidat2_listeelectorale, 456, 296);
  gtk_widget_set_size_request (entrycandidat2_listeelectorale, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycandidat2_listeelectorale), 8226);

  entrycandidat3_listeelectorale = gtk_entry_new ();
  gtk_widget_show (entrycandidat3_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), entrycandidat3_listeelectorale, 456, 368);
  gtk_widget_set_size_request (entrycandidat3_listeelectorale, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycandidat3_listeelectorale), 8226);

  spinbuttonjour_listeelectorale_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjour_listeelectorale = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjour_listeelectorale_adj), 1, 0);
  gtk_widget_show (spinbuttonjour_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonjour_listeelectorale, 448, 432);
  gtk_widget_set_size_request (spinbuttonjour_listeelectorale, 60, 27);

  spinbuttonmois_listeelectorale_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmois_listeelectorale = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmois_listeelectorale_adj), 1, 0);
  gtk_widget_show (spinbuttonmois_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonmois_listeelectorale, 512, 432);
  gtk_widget_set_size_request (spinbuttonmois_listeelectorale, 60, 27);

  spinbuttonannee_listeelectorale_adj = gtk_adjustment_new (1, 2011, 2023, 1, 10, 10);
  spinbuttonannee_listeelectorale = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonannee_listeelectorale_adj), 1, 0);
  gtk_widget_show (spinbuttonannee_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonannee_listeelectorale, 584, 432);
  gtk_widget_set_size_request (spinbuttonannee_listeelectorale, 60, 27);

  label14 = gtk_label_new (_("Jour"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 448, 408);
  gtk_widget_set_size_request (label14, 49, 17);

  label15 = gtk_label_new (_("Mois"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 512, 408);
  gtk_widget_set_size_request (label15, 49, 17);

  label16 = gtk_label_new (_("Annee"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 592, 408);
  gtk_widget_set_size_request (label16, 49, 17);

  label13 = gtk_label_new (_("Candidat 3"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 312, 368);
  gtk_widget_set_size_request (label13, 104, 32);

  label12 = gtk_label_new (_("Candidat 2"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 320, 296);
  gtk_widget_set_size_request (label12, 89, 33);

  label11 = gtk_label_new (_("Candidat 1"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 320, 224);
  gtk_widget_set_size_request (label11, 80, 24);

  label10 = gtk_label_new (_("Orientation"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 312, 144);
  gtk_widget_set_size_request (label10, 104, 32);

  label9 = gtk_label_new (_("Id liste\n"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 328, 72);
  gtk_widget_set_size_request (label9, 72, 32);

  label17 = gtk_label_new (_("Date de creation"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 312, 424);
  gtk_widget_set_size_request (label17, 144, 32);

  buttonajouter_listeelectorale = gtk_button_new ();
  gtk_widget_show (buttonajouter_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonajouter_listeelectorale, 392, 512);
  gtk_widget_set_size_request (buttonajouter_listeelectorale, 128, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonajouter_listeelectorale), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  buttonmodifier_listeelectorale = gtk_button_new ();
  gtk_widget_show (buttonmodifier_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonmodifier_listeelectorale, 592, 512);
  gtk_widget_set_size_request (buttonmodifier_listeelectorale, 128, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonmodifier_listeelectorale), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  comboboxorientation_listeelectorale = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxorientation_listeelectorale);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxorientation_listeelectorale, 456, 144);
  gtk_widget_set_size_request (comboboxorientation_listeelectorale, 168, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxorientation_listeelectorale), _("Droit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxorientation_listeelectorale), _("Gauche"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxorientation_listeelectorale), _("Centre"));

  label2 = gtk_label_new (_("Ajouter/Modifier"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  radiobuttonvoteblanc = gtk_radio_button_new_with_mnemonic (NULL, _("Blanc"));
  gtk_widget_show (radiobuttonvoteblanc);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobuttonvoteblanc, 416, 176);
  gtk_widget_set_size_request (radiobuttonvoteblanc, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonvoteblanc), radiobuttonvoteblanc_group);
  radiobuttonvoteblanc_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonvoteblanc));

  radiobuttonpasdevote = gtk_radio_button_new_with_mnemonic (NULL, _("Pas de vote"));
  gtk_widget_show (radiobuttonpasdevote);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobuttonpasdevote, 568, 176);
  gtk_widget_set_size_request (radiobuttonpasdevote, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonpasdevote), radiobuttonvoteblanc_group);
  radiobuttonvoteblanc_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonpasdevote));

  radiobuttonvoteliste = gtk_radio_button_new_with_mnemonic (NULL, _("Voter une liste"));
  gtk_widget_show (radiobuttonvoteliste);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobuttonvoteliste, 728, 176);
  gtk_widget_set_size_request (radiobuttonvoteliste, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonvoteliste), radiobuttonvoteblanc_group);
  radiobuttonvoteblanc_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonvoteliste));

  buttongotovote = gtk_button_new_with_mnemonic (_("Vote"));
  gtk_widget_show (buttongotovote);
  gtk_fixed_put (GTK_FIXED (fixed4), buttongotovote, 592, 288);
  gtk_widget_set_size_request (buttongotovote, 66, 29);

  label3 = gtk_label_new (_("Vote"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  g_signal_connect ((gpointer) treeview_listeelecotrale, "row_activated",
                    G_CALLBACK (on_treeview_listeelecotrale_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonrecherchelisteelectorale, "clicked",
                    G_CALLBACK (on_buttonrecherchelisteelectorale_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttontri_listeelectorale, "clicked",
                    G_CALLBACK (on_buttontri_listeelectorale_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrefresh_listeelectorale, "clicked",
                    G_CALLBACK (on_buttonrefresh_listeelectorale_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajouter_listeelectorale, "clicked",
                    G_CALLBACK (on_buttonajouter_listeelectorale_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier_listeelectorale, "clicked",
                    G_CALLBACK (on_buttonmodifier_listeelectorale_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonvoteblanc, "toggled",
                    G_CALLBACK (on_radiobuttonvoteblanc_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonpasdevote, "toggled",
                    G_CALLBACK (on_radiobuttonpasdevote_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonvoteliste, "toggled",
                    G_CALLBACK (on_radiobuttonvoteliste_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttongotovote, "clicked",
                    G_CALLBACK (on_buttongotovote_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_listeelectorale, interface_listeelectorale, "interface_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, treeview_listeelecotrale, "treeview_listeelecotrale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, entryidlisteelectoralerecherche, "entryidlisteelectoralerecherche");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, buttonrecherchelisteelectorale, "buttonrecherchelisteelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, image5, "image5");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, buttontri_listeelectorale, "buttontri_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, image4, "image4");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label7, "label7");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, buttonrefresh_listeelectorale, "buttonrefresh_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, image1, "image1");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label4, "label4");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, image6, "image6");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label1, "label1");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, entryid_listeelectorale, "entryid_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, entrycandidat1_listeelectorale, "entrycandidat1_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, entrycandidat2_listeelectorale, "entrycandidat2_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, entrycandidat3_listeelectorale, "entrycandidat3_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, spinbuttonjour_listeelectorale, "spinbuttonjour_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, spinbuttonmois_listeelectorale, "spinbuttonmois_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, spinbuttonannee_listeelectorale, "spinbuttonannee_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label14, "label14");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label15, "label15");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label16, "label16");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label13, "label13");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label12, "label12");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label11, "label11");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label10, "label10");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label9, "label9");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label17, "label17");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, buttonajouter_listeelectorale, "buttonajouter_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, image2, "image2");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label5, "label5");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, buttonmodifier_listeelectorale, "buttonmodifier_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, image3, "image3");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label6, "label6");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, comboboxorientation_listeelectorale, "comboboxorientation_listeelectorale");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label2, "label2");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, radiobuttonvoteblanc, "radiobuttonvoteblanc");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, radiobuttonpasdevote, "radiobuttonpasdevote");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, radiobuttonvoteliste, "radiobuttonvoteliste");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, buttongotovote, "buttongotovote");
  GLADE_HOOKUP_OBJECT (interface_listeelectorale, label3, "label3");

  return interface_listeelectorale;
}

GtkWidget*
create_interface_vote (void)
{
  GtkWidget *interface_vote;
  GtkWidget *fixed5;
  GtkWidget *entryidlistevote;
  GtkWidget *label8;
  GtkWidget *buttonvote;

  interface_vote = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (interface_vote), _("Vote"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (interface_vote), fixed5);

  entryidlistevote = gtk_entry_new ();
  gtk_widget_show (entryidlistevote);
  gtk_fixed_put (GTK_FIXED (fixed5), entryidlistevote, 128, 104);
  gtk_widget_set_size_request (entryidlistevote, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidlistevote), 8226);

  label8 = gtk_label_new (_("Donner id liste a vote"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed5), label8, 72, 64);
  gtk_widget_set_size_request (label8, 256, 32);

  buttonvote = gtk_button_new_with_mnemonic (_("Vote"));
  gtk_widget_show (buttonvote);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonvote, 176, 192);
  gtk_widget_set_size_request (buttonvote, 66, 29);

  g_signal_connect ((gpointer) buttonvote, "clicked",
                    G_CALLBACK (on_buttonvote_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (interface_vote, interface_vote, "interface_vote");
  GLADE_HOOKUP_OBJECT (interface_vote, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (interface_vote, entryidlistevote, "entryidlistevote");
  GLADE_HOOKUP_OBJECT (interface_vote, label8, "label8");
  GLADE_HOOKUP_OBJECT (interface_vote, buttonvote, "buttonvote");

  return interface_vote;
}

